language: python
python:
- '3.3'
- '2.7'
install: pip install -U . --use-mirrors
script: py.test
deploy:
  provider: pypi
  user: aequitas
  password:
    secure: PSw4qGkuDhjeixMpSlmM2GawShS68yMwgoN0raOs4n/8zJPZmWOYuyE1emik07EgxYDpduwh0pCeN57ImsuKcBY7KT7qMnbT5hlFnFQZY3m8Xl7LIxnkA2GIxh2mOEiAY/zXyfGiLVzbwfGjk95vdrPJxmtOInr5ht8/gX49c8w=
  on:
    tags: true
    repo: aequitas/munerator
  distributions: "bdist_wheel"
