language: python
python:
- '3.4'
- '3.3'
- '2.7'
- 'pypy'
before_install:
  - sudo apt-get install libzmq3-dev
install: 
    pip install -U . sphinx --use-mirrors
script: 
    - py.test
    - sphinx-build -n -b html -d _build/doctrees . build/docs
deploy:
  provider: pypi
  user: aequitas
  password:
    secure: "N+b+ne+t9s+tw1kEdA3m0RZtH8ssQCSpuMHe4jjdyThRas9lwB516BFOI9LEg/NGWGsqr5Xc2VKCNQeexp9BMAU3WlLgKqKfmLRe7Jci8U0uTHnfLfcDOJCJ6iCVwwohzIxGEJiYLBNkH7ISYH1Q4jRhVxstTUd/7Vhdc6KW3G8="
  on:
    repo: aequitas/munerator
    branch: master
