language: python
python:
- '3.4'
- '3.3'
- '2.7'
- pypy
before_install:
- sudo apt-get install libzmq3-dev
install: pip install -U . sphinx --use-mirrors
script:
- py.test
- sphinx-build -n -b html -d _build/doctrees . build/docs
deploy:
  provider: pypi
  user: aequitas
  password: 3926eadc46aceef16f54a81ca458d819
  on:
    repo: aequitas/munerator
    branch: master
