language: python
python:
- '3.4'
- '3.3'
- '2.7'
- 'pypy'
before_install:
  - sudo apt-get install libzmq3-dev libsodium-dev

install: pip install -U . --use-mirrors
script: py.test
deploy:
  provider: pypi
  user: aequitas
  password:
    secure: KuVGDWs/KtlAgA7dsgugvzRQHlbP23eI1zdEZ8xGhclkHF8xZjXZKSRQyX/JhHUqsv+HVYweYNUfCL+0m10xM1/O8u+EktmIPsSWSdcw8sUuP3yS59RxXa7Ccg7rOb+Q5XUXHdwkCBrIB4niHhv6PUosn3Hu4XtL/m6spzmT2p8=
  on:
    repo: aequitas/munerator
    branch: master
