language: python
python:
    - '2.7'
    - '3.4'
#    - 'pypy'
before_install: 
    - sudo apt-get install libzmq3-dev
    - pip install -U . wheel --use-mirrors
script: 
    - "make test"
install:
    - "make docs/_build"
    - "make install"
deploy:
    provider: pypi
    user: aequitas
    password:
        secure: To8EeaZoZaZTyAhlzp8dF0FF6ehshEq6En73pDSwB5LcpFVLG7ighStOdhtkEfKbU1SUhUnwTzIPzhGUiNGhU5sFN8t7vV23Hi2s36HKqdhi9cCoRK+l71K7Nys1nJK1IQPWYw69Bx7W3eP3AWst1iTlFfnha7fjPEh1+mfq9gw=
    docs_dir: docs/_build/html
    distributions: "bdist_wheel"
    skip_cleanup: true
    on:
        repo: aequitas/munerator
        branch: master
